source 'https://rubygems.org'

gem 'rake'
gem 'asciidoctor', '1.5.2'
gem 'nokogiri', '~> 1.6.7.rc3'

gem 'json'
gem 'awesome_print'

gem 'asciidoctor-epub3', '1.5.0.alpha.4'
gem 'asciidoctor-pdf', '1.5.0.alpha.9'

gem 'coderay'
gem 'pygments.rb'
gem 'thread_safe'
gem 'epubcheck'